#! /bin/bash

source ./mainMenu

source ./buildApplication
source ./buildDeviceDriver
source ./insertDeviceDriver
source ./watchDeviceDriver
source ./testWithApplication
source ./removeDeviceDriver
source ./exitTestScript
while [ 1 ];
do
	mainMenu
done
