#! /bin/bash

insertDeviceDriver()
{

	read -n2 -p "Enter No Of Devices to be insert:"
	if (insmod ./modules/mycdd.ko nod=$REPLY)
	then
		echo "Device Driver insert Successfully"
	else
		echo "ERROR: Device Driver insert failed"
		read
	fi

}
