#! /bin/bash


mainMenu()
{
	echo "__Main Menu__"
	echo "1. Build Test Applicatio"
	echo "2. Build Device Driver"
	echo "3. Insert Device Driver"
	echo "4. Watch Device Driver"
	echo "5. Test with Application"
	echo "6. Remove Device Driver"
	echo "0. Exit Test Script"

	read -n2 -p "Please Enter Your Choice:"

	case $REPLY in
		1)
			buildApp
			;;
		2)
			buildDeviceDriver
			;;
		3)
			insertDeviceDriver
			;;
		4)
			watchDeviceDriver
			;;
		5)
			testWithApplication
			;;
		6)
			removeDeviceDriver
			;;
		0)
			exitTestScript
			;;
	esac


}
